### ISSUE TITLE
Malformed `left_join()` call

### ISSUE THREAD

**Issue by krlmlr** [dwulff/text2sdg#4]
https://github.com/dwulff/text2sdg/blob/0a2f599f4cedba2fe59bd854fd241b9bc554da5d/R/crosstab.R#L125-L129

The `dplyr::select(document, system, sdg, hit)` will be matched to the `copy` argument. It doesn't raise an error because dplyr currently doesn't force the `copy` argument in this case, but raises an error with duckplyr.

**Comment by psychobas** [comment]
Thanks a lot for noting that @krlmlr! Will this fix immediately.
